name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "Elliptical Orbit"
name = "To Do"

  [[processes.tasks]]
  id = "task3"
  title = "Having the Measurements of the Central Body"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = []

  [[processes.tasks]]
  id = "task4"
  title = "Having the Measurements of First Orbiting Body"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = []

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.progress]]
  id = "task2"
  title = "Researching using Dune and Oplot"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = []

[[processes]]
id = "process3"
name = "Done"
tasks = [ ]

  [[processes.donetasks]]
  id = "task1"
  title = "Research on Elliptical Orbit"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = []